### ISSUE TITLE
Mod isn't loading on (at least some) multiplayer servers

### ISSUE THREAD

**Issue by Ketsuna009** [TheFifthRider/LogSplitter#1]
The mod doesn't load when I joining some multiplayer servers. When I looked into it the same servers were not loading other client-side mods I have. What they seem to all have in common is that they are missing the "side": property in the modinfo.json 

see https://wiki.vintagestory.at/index.php/Modinfo

I don't know why this happens on some servers but not others. It did, for example, load on the official public server.

**Comment by TheFifthRider** [comment]
Interesting! When side isn't present, it seems like side is intended to be interpreted as Universal, which is somewhat a lie for LogSplitter, since it's a client side mod. I've updated the modinfo.json to identify it as such and set both the requiredOnClient and requiredOnServer booleans to false. Would you mind testing this prerelease version to see if the issue is resolved before I tag the official release?
[logsplitter_1.0.1.zip](https://github.com/user-attachments/files/17721332/logsplitter_1.0.1.zip)

**Comment by Ketsuna009** [comment]
That worked fine. Loaded and split the logs as expected

**Comment by TheFifthRider** [comment]
Perfect, I'll tag a release. Thanks for the report!
